name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev --deploy

    - name: Run tests
      run: |
        pipenv run pytest
