name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev --deploy

    - name: Check formatting with black
      run: |
        pipenv run black --check .

    - name: Run tests
      run: |
        pipenv run pytest
